### ISSUE TITLE
Unable to install on ComfyUI Windows Portable version.

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [Big-Idea-Technology/ComfyUI_LLM_Node#3]
There appears to be missing packages/requirements on the portable version that can't be installed.
```
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LLM_Node\__init__.py", line 1, in <module>
    from .LLM_Node import *
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LLM_Node\LLM_Node.py", line 9, in <module>
    from llama_cpp import Llama
ModuleNotFoundError: No module named 'llama_cpp'
```
I tried to manually install  llama-cpp-python but that fails with `ModuleNotFoundError: No module named 'scikit_build_core'`, so I manually installed that and tried again:
```
  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      *** scikit-build-core 0.9.0 using CMake 3.29.0 (wheel)
      *** Configuring CMake...
      2024-04-19 10:17:23,168 - scikit_build_core - WARNING - Can't find a Python library, got libdir=None, ldlibrary=None, multiarch=None, masd=None
      loading initial cache file C:\Users\farre\AppData\Local\Temp\tmpt8rod7sa\build\CMakeInit.txt
      -- Building for: NMake Makefiles
      CMake Error at CMakeLists.txt:3 (project):
        Running

         'nmake' '-?'

        failed with:

         no such file or directory


      CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
      CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
      -- Configuring incomplete, errors occurred!

      *** CMake configuration failed
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects
```
Can the repo be made compatible with the portable version, or is it something I've missed?

**Comment by nazgut** [comment]
Hi do you checked requirements.txt?

**Comment by GalaxyTimeMachine** [comment]
It required VS Code C++ to be installed so it could compile, then it worked.
